In [8]:
import numpy as np 
import pandas as pd 
import json
import pymysql

In [2]:
s = pd.read_csv('Combined.csv')

s

,Unnamed: 0,product title,url,rating,price €,review_count,product
0,0,Hollyland Lark 150 Lavalier Funkmikrofon mit L...,https://www.amazon.com/gp/slredirect/picassoRe...,4.7 / 5,284.00,23.000,DSLR_Camera
1,1,Omegon Fotomontierung Mini Track LX3 N - Reise...,https://www.amazon.com/gp/slredirect/picassoRe...,4.5 / 5,194.00,211.000,DSLR_Camera
2,2,Canon EOS 4000D DSLR Camera and EF-S 18-55 mm ...,https://www.amazon.com/Canon-4000D-Camera-18-5...,4.7 / 5,438.00,1.637,DSLR_Camera
3,3,Canon EOS 2000D Spiegelreflexkamera - mit Obje...,https://www.amazon.com/Canon-Camera-2000D-18-5...,4.7 / 5,417.60,1.284,DSLR_Camera
4,4,Canon EOS 850D DSLR Digitalkamera Gehäuse - mi...,https://www.amazon.com/Canon-850D-DSLR-Digital...,4.7 / 5,849.00,28.000,DSLR_Camera
...,...,...,...,...,...,...,...
14434,14434,Xiaomi Redmi 9 smartphone + headphones (16.59 ...,https://www.amazon.com/-/en/smartphone-headpho...,4.7 / 5,178.67,288.000,Smartphone
14435,14435,"Samsung Galaxy S20 FE, Android SIM Free Smartp...",https://www.amazon.com/-/en/Samsung-Android-Sm...,4.6 / 5,625.00,1.601,Smartphone
14436,14436,"Outdoor Mobile Phone, IIIF150 B2021 Outdoor Sm...",https://www.amazon.com/-/en/gp/slredirect/pica...,4.4 / 5,179.99,64.000,Smartphone
14437,14437,SPC 2350116N Apolo Senior 5 16GB 1GB,https://www.amazon.com/-/en/gp/slredirect/pica...,2.9 / 5,89.90,124.000,Smartphone
14438,14438,"Ulefone Note 9P Smartphone Without Contract, A...",https://www.amazon.com/-/en/gp/slredirect/pica...,4.3 / 5,154.99,2.383,Smartphone

In [28]:
sqlEngine = create_engine('mysql+pymysql://root:Selin_1987@127.0.0.1/amazon', pool_recycle=3600)

dbConnection    = sqlEngine.connect()

# This is for creating data base
sqlEngine.execute("CREATE DATABASE IF NOT EXISTS AMAZON") #create db
sqlEngine.execute("USE AMAZON") # select new db

tableName   = "search_summary"


try:
    frame = s.to_sql(tableName, dbConnection, if_exists='replace',index = False)

except ValueError as vx:
    print(vx)

except Exception as ex:   
    print(ex)

else:
    print("Table %s created successfully."%tableName);   

finally:
    dbConnection.close()

Table search_summary created successfully.